### ISSUE TITLE
Droid48 freezing on Zenfone 2

### ISSUE THREAD

**Issue by mmrsva** [shagr4th/droid48#14]
I don´t know if this is the correct place to post this. Sorry if it's not.

I am having issues with Droid48 (Droid48s too) with my "Zenfone 2". I am a long time user of Droid48 and never had this issue in other phones before. The problem is that, while typing, the app freezes. I try to kill the process, restart the phone, nothing helps. Next time I start the app it's still frozen. The only way to fix is uninstall and reinstall the app again. My guess, this may be related with the fact that Zenfone 2 is Intel-based and not ARM.

Thanks!

Marcio

**Comment by fusterjj** [comment]
I believe this to be a common problem.  I have precisely the same issue on my ARM-based Nexus 5X, so I suspect it doesn't have anything to do with being ARM or not.

It is a bit strange that re-installing is the only way to fix it since the app info shows it doesn't have any data used.

**Comment by dfgweb** [comment]
Closing/killing the running droid48 process allow to unfreeze it. You loose your current stack. Having this bug in Nexus 5X, but also in my old HTC Sensation when testing CM13.

**Comment by shagr4th** [comment]
I do not have any reports of crashing like it used to do, hope it's ok now
