### ISSUE TITLE
Display not updated

### ISSUE THREAD

**Issue by SammysHP** [shagr4th/droid48#16]
The display is updated not often enough. Actually it seems to be updated only after a keypress. There are many situations in which a update is missing, e.g.

- put program on stack: it is shown only after adding something to the stack (=enter)
- switch off calculator and turn it on again: on must be pressed multiple times until the content appears on the screen again.

This is extremely noticeable with SpeedUI which I tested today (and which works great).

**Comment by SammysHP** [comment]
Another example: The clock isn't updated, only on keypresses.

Was also reported in a comment in 2011: https://github.com/shagr4th/droid48/issues/10#issuecomment-2685587

I suggest to update the screen once or twice a second. That shouldn't produce too much load and should be fast enough in most cases.

**Comment by shagr4th** [comment]
I think this one is fixed with the latest commits, clock and cursor are ok
