### ISSUE TITLE
Version discrepancy. 1.74 vs. 1.75

### ISSUE THREAD

**Issue by deverac** [shagr4th/droid48#26]
The page for droid48 at https://www.hpcalc.org/details/7387 says that the current version is 1.75. The most current version on github appears to be 1.74.

The APK included in droid48.zip located on the hpcalc.org page contains version 1.75 (and it looks and behaves differently than version 1.74), however the source files that are included in the zip file are for version 1.74.

I don't need a solution for this; I just thought that you might like to know.

**Comment by shagr4th** [comment]
Thanks for the tip, I just published a new tag
